version: '3.4'

networks:
  mynetwork:
    name: mynetwork
    attachable: true

services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 8443:8443
    volumes:
      - ./myconfig/certs/oidc_simulator.crt:/etc/x509/https/tls.crt
      - ./myconfig/certs/oidc_simulator.key:/etc/x509/https/tls.key
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: host.docker.internal
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    command:
      start-dev
    networks:
      - mynetwork

  f5-oidc:
    container_name: f5-oidc
    build:
      context: ./
      dockerfile: ./docker/nginxplus-25-ubuntu18.04/Dockerfile
    image: f5-oidc
    ports:
      - 443:443
    volumes:
      - ./common/backend:/etc/nginx/backend
      - ./common/oidc:/etc/nginx/oidc
      - ./common/template:/etc/nginx/template
      - ./common/frontend:/usr/share/nginx/html/
      - ./tools/python:/etc/nginx/init
    env_file:
      # Choose and update environment variable file per each IdP
      # - path: ./myconfig/settings-okta.env
      # - path: ./myconfig/settings-keycloak.env
      - path: ./myconfig/settings.env
        required: true
    depends_on:
      - keycloak
    networks:
      - mynetwork
